label: 'Головна сторінка'
tags:
  canonical_url: '[site:url]'
  shortlink: '[site:url]'
  keywords: 'conference, конференція, Drupal, Drupal conference, Kyiv Drupal, Kyiv Drupal Camp, конференція про Друпал, Drupal community'
  description: 'DrupalCamp Kyiv 2017 - головна щорічна подія Drupal-спільноти відбудеться 10-11 червня 2017, в Києві, в готелі “Братислава”'
  og_image: 'http://camp17.drupal.ua/themes/custom/dc17_bootstrap/images/image-for-meta-tags.png'
