module:
  addanother: 0
  admin_toolbar: 0
  adminimal_admin_toolbar: 0
  automated_cron: 0
  backup_migrate: 0
  blazy: 0
  block: 0
  block_content: 0
  breakpoint: 0
  ckeditor: 0
  ckeditor_codemirror: 0
  color: 0
  comment: 0
  config: 0
  config_translation: 0
  contact: 0
  contextual: 0
  crop: 0
  crop_media_entity: 0
  ctools: 0
  datetime: 0
  dblog: 0
  dc2017_master: 0
  dropzonejs: 0
  dropzonejs_eb_widget: 0
  ds_switch_view_mode: 0
  dynamic_page_cache: 0
  editor: 0
  embed: 0
  entity: 0
  entity_browser: 0
  entity_browser_entity_form: 0
  entity_embed: 0
  entity_reference_revisions: 0
  field: 0
  field_group: 0
  field_ui: 0
  file: 0
  file_entity: 0
  filter: 0
  google_analytics: 0
  help: 0
  history: 0
  image: 0
  image_widget_crop: 0
  inline_entity_form: 0
  language: 0
  layout_plugin: 0
  libraries: 0
  link: 0
  locale: 0
  media: 0
  media_entity: 0
  media_entity_document: 0
  media_entity_image: 0
  media_entity_instagram: 0
  media_entity_slideshow: 0
  media_entity_twitter: 0
  menu_ui: 0
  metatag: 0
  metatag_app_links: 0
  metatag_dc: 0
  metatag_dc_advanced: 0
  metatag_hreflang: 0
  metatag_open_graph: 0
  metatag_open_graph_products: 0
  node: 0
  options: 0
  page_cache: 0
  paragraphs: 0
  path: 0
  quickedit: 0
  rdf: 0
  redirect: 0
  redirect_404: 0
  search: 0
  shortcut: 0
  simple_sitemap: 0
  slick: 0
  slick_media: 0
  smtp: 0
  system: 0
  taxonomy: 0
  telephone: 0
  text: 0
  token: 0
  toolbar: 0
  tour: 0
  update: 0
  user: 0
  video_embed_field: 0
  video_embed_media: 0
  video_embed_wysiwyg: 0
  views_infinite_scroll: 0
  views_slideshow: 0
  views_slideshow_cycle: 0
  views_ui: 0
  webform: 0
  webform_ui: 0
  weight: 0
  ds: 1
  menu_link_content: 1
  pathauto: 1
  ds_extras: 2
  content_translation: 10
  views: 10
theme:
  stable: 0
  classy: 0
  bartik: 0
  seven: 0
  adminimal_theme: 0
  bootstrap: 0
  dc17_bootstrap: 0
_core:
  default_config_hash: m2GVq11UAOVuNgj8x0t5fMOPujpvQQ_zxLoaly1BMEU
langcode: uk
